create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 50),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique check (char_length(trim(visitor_id)) between 10 and 100),
  created_at timestamptz not null default now()
);

create index if not exists reviews_created_at_idx on public.reviews(created_at desc);
create index if not exists visitors_created_at_idx on public.visitors(created_at desc);

alter table public.reviews enable row level security;
alter table public.visitors enable row level security;

drop policy if exists "reviews_select_public" on public.reviews;
create policy "reviews_select_public" on public.reviews for select to anon, authenticated using (true);
drop policy if exists "reviews_insert_public" on public.reviews;
create policy "reviews_insert_public" on public.reviews for insert to anon, authenticated with check (char_length(trim(name)) between 1 and 50 and rating between 1 and 5 and char_length(trim(comment)) between 1 and 500);

drop policy if exists "visitors_select_public" on public.visitors;
create policy "visitors_select_public" on public.visitors for select to anon, authenticated using (true);
drop policy if exists "visitors_insert_public" on public.visitors;
create policy "visitors_insert_public" on public.visitors for insert to anon, authenticated with check (char_length(trim(visitor_id)) between 10 and 100);

create or replace function public.get_visitor_count()
returns bigint language sql stable security definer set search_path = public
as $$ select count(*)::bigint from public.visitors; $$;

grant execute on function public.get_visitor_count() to anon, authenticated;
grant select, insert on public.reviews to anon, authenticated;
grant select, insert on public.visitors to anon, authenticated;

do $$ begin
  alter publication supabase_realtime add table public.reviews;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.visitors;
exception when duplicate_object then null; end $$;
